name: Callie

on:
  workflow_call:
  
permissions: 
   pages: write

jobs:
  callie-job:
    runs-on: ubuntu-latest
    steps:
      - name: Callie job
        run: |
              echo "I'm NEW!"
        
