name: Callie

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest
    steps:
      - name: Use a repo or org secret from the calling workflow.
        run: echo -n ${{ secrets.TEST }} | od -A n -t x1
        
  test:
   runs-on: ubuntu-latest
   permissions: 
        issues: write
   steps:
    - name: testing
      run: echo "yoyo"
      
