name: Callie

on:
  workflow_call:
  workflow_dispatch:

permissions: read-all

jobs:
  callie-job:
    runs-on: ubuntu-latest
    steps:
      - name: Callie job
        run: |
          gh api \
            -H "Accept: application/vnd.github.v3+json" \
            /orgs/niccky7/packages?package_type=container
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
