name: ci

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, edited]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: TEST
        run: echo "I'm Child - test2"
