name: Callie

on:
  workflow_call:
  workflow_dispatch:

jobs:
  callie-job:
    runs-on: ubuntu-latest
    steps:
      - name: Callie job
        run: |
          gh api \
            -H "Accept: application/vnd.github.v3+json" \
            /orgs/niccky7/packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
