name: Callie

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Callie job
        run: |
              echo "I'm OLD!"
        
