name: Callie

on:
  workflow_call:
  workflow_dispatch:

jobs:
  callie-job:
    runs-on: ubuntu-latest
    steps:
      - name: Callie job
        run: |
          curl --request GET \
          --url https://api.github.com/orgs/niccky7/packages \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H "Accept: application/vnd.github.v3+json" \
          --fail
